services:
  cruds.property_mapper.jms:
    class: ScayTrase\Api\Cruds\Adaptors\JmsSerializer\JmsPropertyMapper
    arguments:
    - "@jms_serializer.metadata_factory"
    - "@jms_serializer.naming_strategy"

  cruds.jms_serializer:
    class: ScayTrase\Api\Cruds\Adaptors\JmsSerializer\JmsSerializerAdapter
    arguments:
    - "@jms_serializer.serializer"

  cruds.jms_processor:
    class: ScayTrase\Api\Cruds\Adaptors\JmsSerializer\JmsSerializerProcessor
    arguments:
    - "@jms_serializer.serializer"

  cruds.jms_object_constructor:
    class: ScayTrase\Api\Cruds\Adaptors\JmsSerializer\InitializedObjectConstructor
    public: false
    decorates: jms_serializer.unserialize_object_constructor
    arguments:
    - "@cruds.jms_object_constructor.inner"

  cruds.property_mapper:
    alias: cruds.property_mapper.jms
