services:
  cruds.property_mapper.jms:
    class: ScayTrase\Api\Cruds\Adaptors\JmsSerializer\JmsPropertyMapper
    arguments:
    - "@jms_serializer.metadata_factory"

  cruds.jms_serializer:
    class: ScayTrase\Api\Cruds\Adaptors\JmsSerializer\JmsSerializerAdapter
    arguments:
    - "@jms_serializer.serializer"

  cruds.property_mapper:
    alias: cruds.property_mapper.jms
