build:
  tests:
    override:
      -
        command: SERIALIZER=jms phpunit --coverage-clover=build/clover.xml
        coverage:
          file: build/clover.xml
          format: php-clover
      -
        command: SERIALIZER=symfony phpunit --coverage-clover=build/clover.xml
        coverage:
          file: build/clover.xml
          format: php-clover
