build:
  tests:
    override:
      -
        command: SERIALIZER=jms vendor/bin/phpunit --coverage-clover=build/clover.xml
        coverage:
          file: build/clover.xml
          format: php-clover
      -
        command: SERIALIZER=symfony vendor/bin/phpunit --coverage-clover=build/clover.xml
        coverage:
          file: build/clover.xml
          format: php-clover

filter:
  excluded_paths:
    - "./Tests"
    - "./Test"
